export default {
  todos: [
    {
      id: 1,
      todo: "Do something nice for someone you care about",
      completed: false,
      user: 152,
    },
    {
      id: 2,
      todo: "Memorize a poem",
      completed: true,
      user: 13,
    },
    {
      id: 3,
      todo: "Watch a classic movie",
      completed: true,
      user: 68,
    },
    {
      id: 4,
      todo: "Watch a documentary",
      completed: false,
      user: 84,
    },
    {
      id: 5,
      todo: "Invest in cryptocurrency",
      completed: false,
      user: 163,
    },
    {
      id: 6,
      todo: "Contribute code or a monetary donation to an open-source software project",
      completed: false,
      user: 69,
    },
    {
      id: 7,
      todo: "Solve a Rubik's cube",
      completed: true,
      user: 76,
    },
    {
      id: 8,
      todo: "Bake pastries for yourself and neighbor",
      completed: true,
      user: 198,
    },
    {
      id: 9,
      todo: "Go see a Broadway production",
      completed: false,
      user: 7,
    },
    {
      id: 10,
      todo: "Write a thank you letter to an influential person in your life",
      completed: true,
      user: 9,
    },
    {
      id: 11,
      todo: "Invite some friends over for a game night",
      completed: false,
      user: 104,
    },
    {
      id: 12,
      todo: "Have a football scrimmage with some friends",
      completed: false,
      user: 32,
    },
    {
      id: 13,
      todo: "Text a friend you haven't talked to in a long time",
      completed: true,
      user: 2,
    },
    {
      id: 14,
      todo: "Organize pantry",
      completed: false,
      user: 46,
    },
    {
      id: 15,
      todo: "Buy a new house decoration",
      completed: true,
      user: 105,
    },
    {
      id: 16,
      todo: "Plan a vacation you've always wanted to take",
      completed: true,
      user: 162,
    },
    {
      id: 17,
      todo: "Clean out car",
      completed: false,
      user: 71,
    },
    {
      id: 18,
      todo: "Draw and color a Mandala",
      completed: true,
      user: 6,
    },
    {
      id: 19,
      todo: "Create a cookbook with favorite recipes",
      completed: true,
      user: 53,
    },
    {
      id: 20,
      todo: "Bake a pie with some friends",
      completed: false,
      user: 162,
    },
    {
      id: 21,
      todo: "Create a compost pile",
      completed: false,
      user: 13,
    },
    {
      id: 22,
      todo: "Take a hike at a local park",
      completed: true,
      user: 37,
    },
    {
      id: 23,
      todo: "Take a class at local community center that interests you",
      completed: true,
      user: 65,
    },
    {
      id: 24,
      todo: "Research a topic interested in",
      completed: true,
      user: 130,
    },
    {
      id: 25,
      todo: "Plan a trip to another country",
      completed: false,
      user: 140,
    },
    {
      id: 26,
      todo: "Improve touch typing",
      completed: false,
      user: 178,
    },
    {
      id: 27,
      todo: "Learn Express.js",
      completed: false,
      user: 194,
    },
    {
      id: 28,
      todo: "Learn calligraphy",
      completed: false,
      user: 80,
    },
    {
      id: 29,
      todo: "Have a photo session with some friends",
      completed: true,
      user: 91,
    },
    {
      id: 30,
      todo: "Go to the gym",
      completed: true,
      user: 142,
    },
  ],

  users: [
    {
      userId: 152,
      name: "Alice Johnson",
      city: "New York",
      country: "USA",
      phoneNumber: "123-456-7890",
    },
    {
      userId: 13,
      name: "John Smith",
      city: "Los Angeles",
      country: "USA",
      phoneNumber: "234-567-8901",
    },
    {
      userId: 68,
      name: "Emily Brown",
      city: "London",
      country: "UK",
      phoneNumber: "345-678-9012",
    },
    {
      userId: 84,
      name: "Michael Davis",
      city: "Toronto",
      country: "Canada",
      phoneNumber: "456-789-0123",
    },
    {
      userId: 163,
      name: "Sophia Wilson",
      city: "Sydney",
      country: "Australia",
      phoneNumber: "567-890-1234",
    },
    {
      userId: 69,
      name: "Daniel Lee",
      city: "Paris",
      country: "France",
      phoneNumber: "678-901-2345",
    },
    {
      userId: 76,
      name: "Emma White",
      city: "Berlin",
      country: "Germany",
      phoneNumber: "789-012-3456",
    },
    {
      userId: 198,
      name: "Olivia Harris",
      city: "Amsterdam",
      country: "Netherlands",
      phoneNumber: "890-123-4567",
    },
    {
      userId: 7,
      name: "Lucas Clark",
      city: "Dublin",
      country: "Ireland",
      phoneNumber: "901-234-5678",
    },
    {
      userId: 9,
      name: "Ava Martinez",
      city: "Madrid",
      country: "Spain",
      phoneNumber: "012-345-6789",
    },
    {
      userId: 104,
      name: "Mia Anderson",
      city: "Stockholm",
      country: "Sweden",
      phoneNumber: "123-456-7890",
    },
    {
      userId: 32,
      name: "William Thomas",
      city: "Zurich",
      country: "Switzerland",
      phoneNumber: "234-567-8901",
    },
    {
      userId: 2,
      name: "Isabella Moore",
      city: "Vienna",
      country: "Austria",
      phoneNumber: "345-678-9012",
    },
    {
      userId: 46,
      name: "James Taylor",
      city: "Brussels",
      country: "Belgium",
      phoneNumber: "456-789-0123",
    },
    {
      userId: 105,
      name: "Henry Garcia",
      city: "Helsinki",
      country: "Finland",
      phoneNumber: "567-890-1234",
    },
    {
      userId: 162,
      name: "Liam Perez",
      city: "Lisbon",
      country: "Portugal",
      phoneNumber: "678-901-2345",
    },
    {
      userId: 71,
      name: "Charlotte Baker",
      city: "Oslo",
      country: "Norway",
      phoneNumber: "789-012-3456",
    },
    {
      userId: 6,
      name: "Amelia Wright",
      city: "Prague",
      country: "Czech Republic",
      phoneNumber: "890-123-4567",
    },
    {
      userId: 53,
      name: "Benjamin Hill",
      city: "Budapest",
      country: "Hungary",
      phoneNumber: "901-234-5678",
    },
    {
      userId: 37,
      name: "Sophie Scott",
      city: "Warsaw",
      country: "Poland",
      phoneNumber: "012-345-6789",
    },
    {
      userId: 65,
      name: "Jack Nelson",
      city: "Athens",
      country: "Greece",
      phoneNumber: "123-456-7890",
    },
    {
      userId: 130,
      name: "Chloe Carter",
      city: "Vienna",
      country: "Austria",
      phoneNumber: "234-567-8901",
    },
    {
      userId: 140,
      name: "Oliver Murphy",
      city: "Rome",
      country: "Italy",
      phoneNumber: "345-678-9012",
    },
    {
      userId: 178,
      name: "Ella Evans",
      city: "Copenhagen",
      country: "Denmark",
      phoneNumber: "456-789-0123",
    },
    {
      userId: 194,
      name: "Alexander King",
      city: "Edinburgh",
      country: "UK",
      phoneNumber: "567-890-1234",
    },
    {
      userId: 80,
      name: "Harper Robinson",
      city: "Vienna",
      country: "Austria",
      phoneNumber: "678-901-2345",
    },
    {
      userId: 91,
      name: "David Adams",
      city: "Brussels",
      country: "Belgium",
      phoneNumber: "789-012-3456",
    },
    {
      userId: 142,
      name: "Mason Collins",
      city: "Berlin",
      country: "Germany",
      phoneNumber: "890-123-4567",
    },
  ],
};
